### ISSUE TITLE
Introduce ExceptionHandler extension point

### ISSUE THREAD

**Issue by marcphilipp** [junit-team/junit5#103]
## Proposal

```java
interface ExceptionHandlerExtensionPoint extends ExtensionPoint {
   void handleException(TestExtensionContext context, Throwable throwable) throws Throwable;
}
```
### Tasks

- [x] Implement extension point with tests and everything
- [x] Add example usage in documentation
- [x] Introduce `@ExpectToFail` annotation in `document` module to allow sample test cases to fail

related to #92.

**Comment by jlink** [comment]
I'm working on it.

**Comment by sbrannen** [comment]
Cool. Looking forward to having this feature in place!

**Comment by sbrannen** [comment]
By the way, why not just call it `ExceptionHandler`?

I don't see the need to name all extension APIs `*ExtensionPoint`.

**Comment by sbrannen** [comment]
Plus, the `Position` won't make sense with such an `ExceptionHandler`: it can only be used during an _after_ phase, which could be _ordered_, but there is no such concept as _wrapping_ for a feature like this.

This of course ties in with the discussion of `Position` in general which we are discussing in #112.

**Comment by jlink** [comment]
IMO, position makes also sense here since an exception handler can be
closer or further away from the test method itself.

2016-01-21 13:42 GMT+01:00 Sam Brannen <notifications@github.com>:

**Comment by jlink** [comment]
I'm not sure. ExceptionHandler sounds way more generic than it actually is.
Does *ExtensionPoint hurt?

2016-01-21 13:39 GMT+01:00 Sam Brannen <notifications@github.com>:

**Comment by sbrannen** [comment]
> IMO, position makes also sense here since an exception handler can be closer or further away from the test method itself.

Yes, that's what I meant by _ordering_. Ordering certainly makes sense, but wrapping does not. In any case, let's address this topic in #112.

**Comment by sbrannen** [comment]
> Does *ExtensionPoint hurt?

I just question our use of `*ExtensionPoint` in general. I'm not convinced that we need the concept of an "extension point" beyond the basic concept of an "extension".

**Comment by jlink** [comment]
Is it the same discussion we had last week or any other/new points?

`Extension` and `ExtensionPoint` have different semantics in my book. But
we have been through this argument before...

2016-01-21 15:31 GMT+01:00 Sam Brannen <notifications@github.com>:

**Comment by jlink** [comment]
Done with #0684c9c
