### ISSUE TITLE
 Merge milestone and RC release notes for 5.4

### ISSUE THREAD

**Issue by sbrannen** [junit-team/junit5#1749]
## Deliverables

- [x] Merge milestone and RC release notes for 5.4.
- [x] Add special section for changes between RC2 and GA (if necessary).
  - was not necessary
- [x] Consider adding a note under "general improvements" highlighting improvements to the User Guide such as #1651 and #1723.
  - opted instead to mention general improvements in the "Scope" of the release notes.

**Comment by sbrannen** [comment]
_in progress_

**Comment by sbrannen** [comment]
All work for this issue has been pushed to `master`.
