### ISSUE TITLE
Polish Azure Pipelines build

### ISSUE THREAD

**Issue by sormuras** [junit-team/junit5#1810]
After-math for #1807 and closes #1795.

## Deliverables

- [x] Provide credentials to publish SNAPSHOT assets (artifacts and documentation)
- [x] Update https://github.com/junit-team/junit5/blob/master/README.md#continuous-integration-builds table with shields pointing to Azure Pipelines
- [x] Configure "Publish Test Results Job" to include only propery results: https://github.com/junit-team/junit5/pull/1807#discussion_r264530632
- [x] Configure "Checkout task" to only checkout the current branch
- [x] The two last jobs (publish snapshot assets) should only start if "Linux (JDK 11)" was successfully executed
- [x] Remove AppVeyor configuration
- [x] Uninstall/disconnect AppVeyor service
- [x] Remove Travis CI configuration
- [x] Uninstall/disconnect Travis CI service
- [x] ~Configure dependency cache on Azure Pipelines~ will be done in https://github.com/junit-team/junit5/issues/1826

**Comment by sormuras** [comment]
Added the "overall pipeline status badge" via

It is possible to show off all (or some) jobs in a table:

- Linux (OpenJDK 11) 🤜 [![Build Status](https://dev.azure.com/junit-team/junit5/_apis/build/status/junit-team.junit5?branchName=master&jobName=Linux%20(OpenJDK%2011))](https://dev.azure.com/junit-team/junit5/_build/latest?definitionId=1&branchName=master)
- Linux (OpenJDK 12) 🤜 [![Build Status](https://dev.azure.com/junit-team/junit5/_apis/build/status/junit-team.junit5?branchName=master&jobName=Linux%20(OpenJDK%2012))](https://dev.azure.com/junit-team/junit5/_build/latest?definitionId=1&branchName=master)
- Linux (OpenJDK 13) 🤜 [![Build Status](https://dev.azure.com/junit-team/junit5/_apis/build/status/junit-team.junit5?branchName=master&jobName=Linux%20(OpenJDK%2013))](https://dev.azure.com/junit-team/junit5/_build/latest?definitionId=1&branchName=master)

**Comment by sormuras** [comment]
> Click **Advanced settings** in the **Get Sources** task to see some of the above options.

I can't find the "Advanced settings..." described here https://docs.microsoft.com/en-us/azure/devops/pipelines/repos/pipeline-options-for-git?view=azure-devops to activate

**Comment by ethomson** [comment]
> I can't find the "Advanced settings..." described here https://docs.microsoft.com/en-us/azure/devops/pipelines/repos/pipeline-options-for-git?view=azure-devops to activate the "Shallow fetch" option.

Sorry for the confusion - we have two independent ways to configure CI, either the visual designer or the YAML.  It's pretty much all or nothing (all visual designer or all YAML) and those instructions guide you to the visual designer path.  We're using YAML which is right and true, so I opened #1812 to add the shallow clone rules to the YAML.

**Comment by sormuras** [comment]
Understood.

We are trying to insert our secret credentials via UI right now. Looking forward to merge #1812 and proceed with the switch.

**Comment by sormuras** [comment]
**Current status**

![image](https://user-images.githubusercontent.com/2319838/54219214-5d051f00-44ef-11e9-94ef-d113a92f912c.png)

**Todo**

- [ ] The two last jobs should only start if the five above were successfully executed.

**Comment by ethomson** [comment]
>  The two last jobs should only start if the five above were successfully executed.

Should be something like:

```
- job: publish_artifacts
  displayName: Publish Snapshot Artifacts
  dependsOn:
  - linux_11
  - linux_12
  - Mac
  - Windows
  - coverage
```

@sormuras I can send a PR unless you're in the middle of this.

**Comment by sormuras** [comment]
About to push it in a second... ;-)

**Comment by sormuras** [comment]
See https://github.com/junit-team/junit5/commit/6706691072bc122b0f54c91856452db1d644e4aa ... chose `linux_11` as single dependency for now.

**Comment by sormuras** [comment]
Waiting as expected...

![image](https://user-images.githubusercontent.com/2319838/54221971-c6d3f780-44f4-11e9-91e9-baff7ae3f5f6.png)

**Comment by sormuras** [comment]
@ethomson ... those two publish/update jobs (and the coverage job as well) are good candidates for a dedicated "Release Pipeline", aren't they?

**Comment by ethomson** [comment]
> those two publish/update jobs (and the coverage job as well) are good candidates for a dedicated "Release Pipeline", aren't they?

@sormuras - I actually would not in this case.  There's a couple of reasons:

1. Pipelines are really useful when you have additional levels of complexity.  For example: if you want to deploy to a staging server, then QA, then production, pipelines help manage that.  They're still useful for a single deployment like this but you're not taking advantage of a lot of the complex parts.

2. It also adds a complication, related to the first point: since pipelines are created for a way to arbitrarily deploy artifacts, you need to _build_ an artifact.  So you'll probably run `./gradlew --scan publish -x check` then zip up the artifacts and publish them.  Then your release pipeline will take that zip and do the publish.  So it's slower and has another moving piece.

3. Release pipelines can't be defined as YAML (yet).

So, to be honest, I would keep this as-is for now, it's simpler and gets the job done.  If you want to scale things up or increase the complexity then it makes sense to reconsider.

**Comment by sormuras** [comment]
Keeping things as-is. Thanks for the details.

**Comment by sormuras** [comment]
Updated deliverables with "clean up" entries.

**Comment by sormuras** [comment]
**Performance comparison**
- Travis [9 minutes 14 seconds](https://travis-ci.org/junit-team/junit5/builds/505588712)
- Azure [9 minutes 7 seconds](https://dev.azure.com/junit-team/junit5/_build/results?buildId=47)

**But**
- Travis spent [10 seconds](https://travis-ci.org/junit-team/junit5/builds/505588712#L444) to restore cached `/home/travis/.gradle/caches` [scan](https://scans.gradle.com/s/tlcv5m3go3aia/performance/build)
- Azure spent 2 minutes 24 seconds on downloading plugins and dependencies [scan](https://scans.gradle.com/s/4dh3oldtzuivw/performance/networkActivity)

**Comment by sormuras** [comment]
Caching is not yet supported at Azure Pipelines: https://devblogs.microsoft.com/devops/adding-caching-to-azure-pipelines/

**Comment by ethomson** [comment]
![VPffJLd](https://user-images.githubusercontent.com/1130014/54272817-51ac0500-457c-11e9-8872-2c49941a3adb.gif)

**Comment by marcphilipp** [comment]
I guess we could build our own Docker image with a "pre-warmed" cache but it's probably not worth the complexity.

**Comment by sormuras** [comment]
Let's wait for ... "SOON".

**Comment by sormuras** [comment]
"Publish" jobs were executed although "Build+Test" jobs failed?

![image](https://user-images.githubusercontent.com/2319838/54473579-0b53e180-47da-11e9-8861-6ec8334b0609.png)

**Comment by marcphilipp** [comment]
We'll look into caching dependencies in https://github.com/junit-team/junit5/issues/1826.
