### ISSUE TITLE
Prune Release Notes for 5.5

### ISSUE THREAD

**Issue by sbrannen** [junit-team/junit5#1935]
## Overview

_Prune_ the release notes like we have done previously (see ef576cafe55e62e69a0cca8940e342c64f6d8ee5).

## Deliverables

- [x] ~Document #1929 in the Release Notes.~ done in 9cf05a36d624535628ea31183f90d7e6eca95772
- [x] ~Document #1932 in the Release Notes.~ done in 9cf05a36d624535628ea31183f90d7e6eca95772
- [x] ~Document #1934 in the Release Notes.~ done in 9cf05a36d624535628ea31183f90d7e6eca95772
- [x] ~Document #1925 in the Release Notes.~ done in 9cf05a36d624535628ea31183f90d7e6eca95772
- [ ] Prune Release Notes for 5.5.

**Comment by sbrannen** [comment]
_in progress_
