### ISSUE TITLE
Introduce a Unique ID tracking TestExecutionListener

### ISSUE THREAD

**Issue by sbrannen** [junit-team/junit5#2619]
## Overview

Inspired by the simple [`TestClassTrackingTestExecutionListener`](https://github.com/sbrannen/spring-framework/blob/77a115f7172b5b8874391ccfb4ffd800c0b4ba1e/spring-core/src/testFixtures/java/org/springframework/core/testfixture/junit/platform/TestClassTrackingTestExecutionListener.java) that I introduced as a proof of concept in the test suite for the Spring Framework, we should introduce a `UniqueIdTrackingListener` as an implementation of the `TestExecutionListener` API for the JUnit Platform.

`UniqueIdTrackingListener` would track the unique IDs of all "tests" (not containers) that were executed during the execution of test plan. It would track all tests, regardless of the success/failure status of the test, and write the unique IDs to a text file.

The text file can then be used by a build tool or plugin to execute the same set of tests again without having to query the user configuration for the test plan and without having to perform classpath scanning again to discover tests.

This can be useful for test environments such as within a native image -- for example, a GraalVM native image -- in order to rerun the exact same tests from a standard JVM test run within a native image.

## Deliverables

- [x] Introduce `UniqueIdTrackingListener` in the `junit-platform-launcher` module.
- [x] Register the `UniqueIdTrackingListener` by default via Java's `ServiceLoader` mechanism.
- [x] Make the `UniqueIdTrackingListener` an opt-in feature. If a specific JVM system property has not been set to `true`, the registered `UniqueIdTrackingListener` would serve as a no-op listener and not do anything.
- [x] Make the output directory and output file configurable.
- [x] Make the output directory convention-based by default, choosing an appropriate build directory for Maven or Gradle, depending on the presence of `pom.xml` or `*.gradle`/`*.gradle.kts` respectively.
- [x] Document `UniqueIdTrackingListener` in Javadoc.
- ❌ Document `UniqueIdTrackingListener` in the User Guide.
  - Since the User Guide currently has no section dedicated to `TestExecutionListener` implementations, this will be addressed in a separate issue.
- [x] Document `UniqueIdTrackingListener` in the Release Notes.

**Comment by sbrannen** [comment]
Reopening this issue in order to track _skipped_ tests as well.

**Comment by sbrannen** [comment]
Reopening to support concurrent use cases. See https://github.com/graalvm/native-build-tools/issues/84 for details.
