### ISSUE TITLE
Finish and promote open-test-reporting format

### ISSUE THREAD

**Issue by marcphilipp** [junit-team/junit5#4113]
The Open Test Reporting format was introduced to replace the legacy XML format for test results in a way that supports all features of JUnit 5. It's designed to alleviate users from the mental load of having to translate from the logical structure of their test cases to an outdated technical format and vice versa. This task adds the missing pieces to make it truly useful and superior to the old format. This will reduce friction for our users by making it easier to understand test results and find the root cause of test failures and also make triaging bug reports easier for maintainers in the future because they will be able to request a test report which contains all relevant information.

## Deliverables/tasks

- [x] Add a converter from XML to HTML for Open Test Reporting format:
	- [x] ota4j-team/open-test-reporting#159
	- [x] ota4j-team/open-test-reporting#167
	- [x] ota4j-team/open-test-reporting#170
	- [x] #4116
	- [x] ota4j-team/open-test-reporting#174
	- [x] ota4j-team/open-test-reporting#178
- [x] Add optional support for source control metadata (for example, Git commit ID) to test reports
	- [x] ota4j-team/open-test-reporting#180
	- [x] #4126
	- [x] #4161
- [x] Add support for attaching files such as screenshots to test results
	- [x] ota4j-team/open-test-reporting#185
	- [x] #4138
	- [x] ota4j-team/open-test-reporting#203
	- [x] ota4j-team/open-test-reporting#207
	- [x] #4165
	- [x] ota4j-team/open-test-reporting#209
- [x] Reach out to testing framework maintainers in other ecosystems and ask for feedback
	- https://github.com/cucumber/cucumber-jvm/issues/2947
	- https://github.com/pytest-dev/pytest/issues/13045
	- https://github.com/mochajs/mocha/issues/5271
	- https://github.com/spockframework/spock/issues/2049
	- https://github.com/sebastianbergmann/phpunit/issues/6077

**Comment by arukiidou** [comment]
[GitLab Unit test reports](https://docs.gitlab.com/ci/testing/unit_test_reports/) did not supports Open Test Report yet.

GitLab is not testing framework, but they receive JUnit format and display.   
It might also be worth to seek feedback from ecosystems that receive `legacy XML format`.

[GitLab Issues: Support for Open Test Report format for test results](https://gitlab.com/gitlab-org/gitlab/-/issues/545747)
