### ISSUE TITLE
Improve naming of command-line options for ConsoleLauncher

### ISSUE THREAD

**Issue by sbrannen** [junit-team/junit5#468]
## Overview

Since we are planning on introducing several new command-line options for the `ConsoleLauncher` over the next few milestone releases, now is a good time to ensure that we have consistent, meaningful naming in place.

## Changes to Enact

The following existing options should be removed.

- [x] `-C`: for disabling ANSI colors
- [x] `-D`: for hiding details
- [x] `-r`: for the XML reports directory

The following existing options should be renamed.

- [x] `-a` | `--all` ==> `--scan-class-path`
- [x] `--xml-reports-dir` ==> `--reports-dir`

## Proposed Options

The following constitute the final set of options based on current known requirements.

### General Purpose

- [x] `-cp` |  `--classpath` | `--class-path`: provide additional classpath entries
- [x] `--disable-ansi-colors`
- [x] `-h`  |  `--help`
- [x] `--hide-details`
- [x] `--reports-dir`: output directory for test reports (e.g., XML, JSON, etc.)

### Selectors

- [x] `--scan-class-path`: scan all classpath roots
- [x] `-c` |  `--select-java-class`: addressed in #437
- [x] `-d` |  `--select-directory`: addressed in #453
- [x] `-f` |  `--select-file`: addressed in #453
- [x] `-p` |  `--select-java-package`: addressed in #437
- [x] `-m` |  `--select-java-method`: addressed in #437
- [x] `-r` |  `--select-resource`: select classpath resource: addressed in #452
- [x] `-u` |  `--select-uri`: addressed in #470

### Filters

- [x] `-e` |  `--include-engine`
- [x] `-E` |  `--exclude-engine`
- [x] `-n` |  `--include-classname`
- [x] `-t` |  `--include-tag`
- [x] `-T` |  `--exclude-tag`

**Comment by marcphilipp** [comment]
LGTM! 👍

**Comment by sbrannen** [comment]
*Team Decision*: implement proposal.

**Comment by sbrannen** [comment]
_in progress_

**Comment by sbrannen** [comment]
Closing this issue since all tasks have either been performed or will be performed in related, open issues.
